-- Optional development sample inventory. Existing rows are never updated.
INSERT INTO blog_posts (id, category, title, excerpt, content, image_fallback_color, image_url, published_at, read_time)
VALUES
  ('blog-1', 'Travel Tips', '10 Essential Items to Pack for a Beach Vacation', 'Don''t let a forgotten item ruin your sunny getaway. Here is our ultimate packing list for the perfect beach trip.', 'A thoughtful packing list keeps a beach holiday relaxed from the first morning to the last sunset. Pack light layers, sun protection, swimwear, comfortable footwear, a reusable water bottle, and a small dry bag for your essentials.', 'bg-[var(--color-primary-soft)]', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=900&q=85', '2023-10-12', '5 min read'),
  ('blog-2', 'Destinations', 'Hidden Gems in Europe You Need to Visit', 'Skip the crowded tourist traps and explore these beautiful, lesser-known European destinations on your next trip.', 'Europe rewards travelers who leave room for detours. Look beyond the headline cities for quiet coastal towns, historic villages, and local food markets where a slower itinerary creates the best memories.', 'bg-[var(--color-secondary-soft)]', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?w=900&q=85', '2023-11-05', '8 min read'),
  ('blog-3', 'Visa Guide', 'Navigating the Schengen Visa Process', 'A comprehensive, step-by-step guide to applying for a Schengen visa for your upcoming European adventure.', 'Start your Schengen application early and keep your documents consistent. Check the consulate requirements for your main destination, prepare proof of accommodation and travel insurance, and allow time for an appointment and processing.', 'bg-[var(--color-accent-soft)]', 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=900&q=85', '2024-01-20', '10 min read'),
  ('blog-4', 'Budget Travel', 'How to Travel India on ₹500 a Day', 'Smart budgeting tips for exploring India without breaking the bank. From street food to budget stays.', 'A flexible daily budget can take you a long way in India. Use local transport, choose regional food, book simple stays, and keep a small reserve for experiences that are worth the extra rupees.', 'bg-[var(--color-primary-soft)]', 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=900&q=85', '2024-02-14', '7 min read'),
  ('blog-5', 'Travel Tips', 'Business Travel: Packing Light for Short Trips', 'Master the art of minimalist packing for business trips. Look sharp with just a carry-on bag.', 'The easiest business trip to manage is the one that fits in a carry-on. Build a small capsule wardrobe around versatile pieces, keep chargers together, and leave space for anything you may bring home.', 'bg-[var(--color-secondary-soft)]', 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=900&q=85', '2024-03-08', '4 min read'),
  ('blog-6', 'Destinations', 'Best Hill Stations to Visit in India This Summer', 'Escape the heat with these stunning hill stations across India. From Shimla to Munnar, plan your perfect getaway.', 'India''s hill stations offer very different landscapes and rhythms. Compare weather, travel time, and local activities before choosing between a quiet mountain retreat, a tea-growing region, or a lively heritage town.', 'bg-[var(--color-accent-soft)]', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=900&q=85', '2024-04-22', '6 min read')
ON CONFLICT (id) DO NOTHING;
INSERT INTO travel_packages (id, destination, duration, description, starting_price, highlights, image_fallback_color, image_url, category, price_amount, currency)
VALUES
  ('pkg-1', 'Swiss Alps Explorer', '7 Days, 6 Nights', 'Experience the breathtaking beauty of the Swiss Alps with scenic train rides and cozy stays.', 'From INR 129,900 (Sample)', ARRAY['Scenic Train Rides', 'Mountain Tours', 'Breakfast Included'], 'bg-[var(--color-secondary-soft)]', 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=1200&q=85', 'international', 129900, 'INR'),
  ('pkg-2', 'Tropical Maldives', '5 Days, 4 Nights', 'Relax in overwater villas and enjoy the crystal-clear waters of the Indian Ocean.', 'From INR 89,900 (Sample)', ARRAY['Overwater Villa', 'Snorkeling', 'All-Inclusive'], 'bg-[var(--color-accent-soft)]', 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&q=85', 'international', 89900, 'INR'),
  ('pkg-3', 'Cultural Japan', '10 Days, 9 Nights', 'Discover the perfect blend of ancient traditions and modern technology in Japan.', 'From INR 189,900 (Sample)', ARRAY['Tokyo City Tour', 'Kyoto Temples', 'Bullet Train Pass'], 'bg-[var(--color-primary-soft)]', 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=85', 'international', 189900, 'INR'),
  ('pkg-national-delhi', 'Delhi Heritage Trail', '3 Days, 2 Nights', 'Explore Mughal landmarks, lively markets, and the historic heart of India.', 'From INR 18,900', ARRAY['Red Fort', 'India Gate', 'Old Delhi Food Walk'], 'bg-[var(--color-secondary-soft)]', 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200&q=85', 'national', 18900, 'INR'),
  ('pkg-national-punjab', 'Punjab Culture & Countryside', '4 Days, 3 Nights', 'Experience Punjabi hospitality, flavorful cuisine, and vibrant countryside traditions.', 'From INR 24,900', ARRAY['Golden Temple', 'Punjabi Cuisine', 'Village Experience'], 'bg-[var(--color-accent-soft)]', 'https://images.unsplash.com/photo-1609947017136-9daf32a5eb16?w=1200&q=85', 'national', 24900, 'INR'),
  ('pkg-national-amritsar', 'Amritsar Spiritual Escape', '3 Days, 2 Nights', 'Discover Amritsar through its sacred landmarks, history, and unforgettable local flavors.', 'From INR 16,900', ARRAY['Golden Temple', 'Wagah Border', 'Jallianwala Bagh'], 'bg-[var(--color-primary-soft)]', 'https://images.unsplash.com/photo-1609947017136-9daf32a5eb16?w=1200&q=85', 'national', 16900, 'INR'),
  ('pkg-national-goa', 'Goa Beach Getaway', '5 Days, 4 Nights', 'Unwind on Goa beaches with coastal food, heritage walks, and easy island time.', 'From INR 29,900', ARRAY['Beach Time', 'Old Goa Churches', 'Coastal Cuisine'], 'bg-[var(--color-accent-soft)]', 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&q=85', 'national', 29900, 'INR'),
  ('pkg-national-kashmir', 'Kashmir Valley Escape', '6 Days, 5 Nights', 'Travel through serene valleys, mountain views, and the calm waters of Dal Lake.', 'From INR 39,900', ARRAY['Dal Lake', 'Gulmarg', 'Pahalgam'], 'bg-[var(--color-secondary-soft)]', 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=1200&q=85', 'national', 39900, 'INR'),
  ('pkg-national-kerala', 'Kerala Backwaters & Hills', '6 Days, 5 Nights', 'Combine peaceful backwaters, lush hill country, and Kerala cultural experiences.', 'From INR 34,900', ARRAY['Houseboat Stay', 'Munnar Hills', 'Kerala Cuisine'], 'bg-[var(--color-primary-soft)]', 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=85', 'national', 34900, 'INR')
ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_services (id, country, visa_type, processing_time, starting_from, image_url, documents)
VALUES
  ('visa-1', 'United Kingdom', 'Standard Visitor Visa', '15 to 30 working days', 'From INR 4,999', 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=900&q=85', ARRAY['Passport', 'Bank Statement', 'Travel Itinerary', 'Hotel Booking']),
  ('visa-2', 'France', 'Schengen Tourist Visa', '15 working days', 'From INR 3,499', 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=900&q=85', ARRAY['Passport', 'Travel Insurance', 'Flight Booking', 'Bank Statement']),
  ('visa-3', 'Australia', 'Visitor Visa (Subclass 600)', '20 to 35 working days', 'From INR 5,499', 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=900&q=85', ARRAY['Passport', 'Bank Statement', 'Employment Letter', 'Travel Plan']),
  ('visa-4', 'United States', 'B1/B2 Tourist Visa', '3 to 6 weeks', 'From INR 14,999', 'https://images.unsplash.com/photo-1485738422979-f5c462d49f04?w=900&q=85', ARRAY['Passport', 'DS-160 Confirmation', 'Photo', 'Bank Statement']),
  ('visa-5', 'Singapore', 'Tourist Visa', '5 to 7 working days', 'From INR 2,499', 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=900&q=85', ARRAY['Passport', 'Photo', 'Bank Statement', 'Flight Booking']),
  ('visa-6', 'Thailand', 'Tourist Visa on Arrival', '1 to 2 working days', 'From INR 1,999', 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=900&q=85', ARRAY['Passport', 'Photo', 'Return Ticket', 'Hotel Booking'])
ON CONFLICT (id) DO NOTHING;

INSERT INTO coupons (code, discount_type, discount_value, min_order_paise, max_discount_paise, valid_until, applicable_on)
VALUES
  ('FIRST10', 'percentage', 10, 100000, 50000, '2026-12-31', ARRAY['flights', 'hotels', 'bus', 'trains', 'packages']),
  ('FLY500', 'flat', 500, 300000, 50000, '2026-11-30', ARRAY['flights']),
  ('HOLIDAY20', 'percentage', 20, 500000, 200000, '2026-10-31', ARRAY['packages'])
ON CONFLICT (code) DO NOTHING;

INSERT INTO bus_services (id, operator, origin, destination, departure_time, arrival_time, duration_minutes, duration_label, bus_type, price, seats_left, metadata)
VALUES
  ('bus-1', 'LemonLine Express', 'Delhi', 'Jaipur', '06:30', '11:15', 285, '4h 45m', 'Volvo AC Sleeper', 899, 8, '{"amenities":["wifi","charging","blanket"],"boardingPoints":["Kashmere Gate ISBT"],"dropPoints":["Sindhi Camp"],"cancellation":"Free cancellation up to 6 hours before departure."}'::jsonb),
  ('bus-2', 'CityRide', 'Mumbai', 'Pune', '08:00', '11:30', 210, '3h 30m', 'AC Seater', 549, 14, '{"amenities":["wifi","charging"],"boardingPoints":["Dadar","Borivali"],"dropPoints":["Shivajinagar"],"cancellation":"Free cancellation up to 6 hours before departure."}'::jsonb),
  ('bus-3', 'Coastal Connect', 'Bengaluru', 'Goa', '21:15', '07:00', 585, '9h 45m', 'Premium Sleeper', 1299, 5, '{"amenities":["wifi","charging","blanket","water"],"boardingPoints":["Electronic City"],"dropPoints":["Panaji"],"cancellation":"Partial refund up to 12 hours before departure."}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO train_services (id, train_number, name, origin, destination, departure_time, arrival_time, duration_label, classes, price_amount, currency)
VALUES
  ('train-1', '12951', 'Mumbai Rajdhani', 'Mumbai', 'Delhi', '17:00', '08:35', '15h 35m', ARRAY['1A', '2A', '3A'], 2450, 'INR'),
  ('train-2', '12002', 'Bhopal Shatabdi', 'New Delhi', 'Bhopal', '06:00', '14:40', '8h 40m', ARRAY['CC', 'EC'], 1280, 'INR'),
  ('train-3', '22691', 'Rajdhani Express', 'Bengaluru', 'New Delhi', '20:20', '05:55', '33h 35m', ARRAY['2A', '3A'], 2150, 'INR')
ON CONFLICT (id) DO NOTHING;

INSERT INTO hotels (id, name, city, area, property_type, star_rating, guest_rating, guest_review_count, starting_price, description, catalog)
VALUES
  ('h1', 'The Grand Imperial', 'Delhi', 'Connaught Place', 'hotel', 5, 4.6, 2340, 8500,
   'A landmark heritage property in the heart of New Delhi, blending colonial grandeur with contemporary luxury. Elegant rooms, award-winning dining, and a rooftop pool overlooking the city skyline.',
   $$ {
     "location": {"city":"Delhi","area":"Connaught Place","address":"12 Barakhamba Road, Connaught Place","landmark":"Near Rajiv Chowk Metro"},
     "images": [{"url":"https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800","alt":"Hotel exterior at dusk","category":"exterior"},{"url":"https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800","alt":"Luxury suite bedroom","category":"room"}],
     "amenities": ["wifi","pool","gym","spa","restaurant","bar","parking","room_service","laundry","business_center","ac"],
     "checkInTime":"14:00","checkOutTime":"12:00",
     "rooms": [{"id":"h1-r1","name":"Superior Room","type":"standard","description":"Well-appointed room with city views, marble bathroom, and premium bedding.","maxOccupancy":{"maxAdults":2,"maxChildren":1,"maxTotal":3},"bedType":"1 King Bed","amenities":["minibar","safe","work desk","rain shower"],"images":[],"availableQuantity":5,"rates":[{"id":"h1-r1-ro","name":"Room Only","pricePerNight":8500,"currency":"INR","mealPlan":"room_only","refundable":false,"cancellationPolicy":"Non-refundable. No cancellation allowed.","benefits":[]},{"id":"h1-r1-bb","name":"Bed & Breakfast","pricePerNight":9100,"currency":"INR","mealPlan":"breakfast","refundable":true,"cancellationPolicy":"Free cancellation up to 24 hours before check-in.","benefits":["Buffet breakfast included"]}]},
              {"id":"h1-r2","name":"Deluxe Room","type":"deluxe","description":"Spacious room with panoramic views, walk-in closet, and a sitting area.","maxOccupancy":{"maxAdults":2,"maxChildren":2,"maxTotal":4},"bedType":"1 King Bed or 2 Twin Beds","amenities":["minibar","safe","work desk","bathtub","balcony"],"images":[],"availableQuantity":5,"rates":[{"id":"h1-r2-bb","name":"Bed & Breakfast","pricePerNight":11200,"currency":"INR","mealPlan":"breakfast","refundable":true,"cancellationPolicy":"Free cancellation up to 24 hours before check-in.","benefits":["Buffet breakfast included"]}]}]
   } $$::jsonb),
  ('h2', 'Seaside Breeze Resort', 'Goa', 'Calangute', 'resort', 4, 4.3, 1870, 5200,
   'A vibrant beachfront resort with tropical gardens, multiple pools, and direct access to Calangute beach. Perfect for families and couples seeking a sun-soaked getaway.',
   $$ {
     "location": {"city":"Goa","area":"Calangute","address":"Beach Road, Calangute","landmark":"Direct beach access"},
     "images": [{"url":"https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800","alt":"Resort pool with ocean view","category":"pool"},{"url":"https://images.unsplash.com/photo-1590490360182-c33d955bc27d?w=800","alt":"Beach facing room","category":"room"}],
     "amenities": ["wifi","pool","gym","spa","restaurant","bar","parking","room_service","ac","breakfast"],
     "checkInTime":"15:00","checkOutTime":"11:00",
     "rooms": [{"id":"h2-r1","name":"Garden View Room","type":"standard","description":"Comfortable room overlooking the tropical gardens with modern amenities.","maxOccupancy":{"maxAdults":2,"maxChildren":1,"maxTotal":3},"bedType":"1 Queen Bed","amenities":["minibar","safe","garden view"],"images":[],"availableQuantity":5,"rates":[{"id":"h2-r1-ro","name":"Room Only","pricePerNight":5200,"currency":"INR","mealPlan":"room_only","refundable":false,"cancellationPolicy":"Non-refundable. No cancellation allowed.","benefits":[]},{"id":"h2-r1-bb","name":"Bed & Breakfast","pricePerNight":5800,"currency":"INR","mealPlan":"breakfast","refundable":true,"cancellationPolicy":"Free cancellation up to 24 hours before check-in.","benefits":["Buffet breakfast included"]}]},
              {"id":"h2-r2","name":"Sea View Deluxe","type":"deluxe","description":"Bright room with a private balcony facing the Arabian Sea.","maxOccupancy":{"maxAdults":2,"maxChildren":2,"maxTotal":4},"bedType":"1 King Bed","amenities":["minibar","balcony","sea view","safe"],"images":[],"availableQuantity":5,"rates":[{"id":"h2-r2-bb","name":"Bed & Breakfast","pricePerNight":7800,"currency":"INR","mealPlan":"breakfast","refundable":true,"cancellationPolicy":"Free cancellation up to 24 hours before check-in.","benefits":["Buffet breakfast included"]}]}]
   } $$::jsonb),
  ('h3', 'Mountain Trail Lodge', 'Manali', 'Old Manali', 'boutique', 3, 4.1, 920, 2800,
   'A cozy mountain lodge surrounded by pine forests, offering stunning valley views, a crackling fireplace lounge, and easy access to hiking trails and adventure activities.',
   $$ {
     "location": {"city":"Manali","area":"Old Manali","address":"Hadimba Road, Old Manali","landmark":"Near Hadimba Temple"},
     "images": [{"url":"https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800","alt":"Lodge exterior in the mountains","category":"exterior"},{"url":"https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800","alt":"Cozy room with mountain view","category":"room"}],
     "amenities": ["wifi","restaurant","parking","room_service","laundry"],
     "checkInTime":"13:00","checkOutTime":"11:00",
     "rooms": [{"id":"h3-r1","name":"Valley View Room","type":"standard","description":"Simple, warm room with a window overlooking the Kullu valley.","maxOccupancy":{"maxAdults":2,"maxChildren":1,"maxTotal":3},"bedType":"1 Double Bed","amenities":["heater","hot water","valley view"],"images":[],"availableQuantity":5,"rates":[{"id":"h3-r1-ro","name":"Room Only","pricePerNight":2800,"currency":"INR","mealPlan":"room_only","refundable":false,"cancellationPolicy":"Non-refundable. No cancellation allowed.","benefits":[]},{"id":"h3-r1-bb","name":"Bed & Breakfast","pricePerNight":3400,"currency":"INR","mealPlan":"breakfast","refundable":true,"cancellationPolicy":"Free cancellation up to 24 hours before check-in.","benefits":["Breakfast included"]}]},
              {"id":"h3-r2","name":"Pine Deluxe Room","type":"deluxe","description":"Larger room with wooden interiors, a writing desk, and forest views.","maxOccupancy":{"maxAdults":2,"maxChildren":2,"maxTotal":4},"bedType":"1 King Bed","amenities":["heater","hot water","forest view","work desk","sitting area"],"images":[],"availableQuantity":5,"rates":[{"id":"h3-r2-bb","name":"Bed & Breakfast","pricePerNight":4200,"currency":"INR","mealPlan":"breakfast","refundable":true,"cancellationPolicy":"Free cancellation up to 24 hours before check-in.","benefits":["Breakfast included"]}]}]
   } $$::jsonb)
ON CONFLICT (id) DO NOTHING;
